### ISSUE TITLE
xattr: No such file: /Applications/EasyYeelight.app

### ISSUE THREAD

**Issue by zyllwy** [xs0521/EasyYeelight#1]
xattr: No such file: /Applications/EasyYeelight.app

**Comment by xs0521** [comment]
<img width="728" alt="Xnip2024-12-10_21-24-59" src="https://github.com/user-attachments/assets/e1261980-7ece-45aa-a4c2-93dd0eba0506">

Before doing so, drag the applicaiton to the Application folder

**Comment by lsongdev** [comment]
Project name is `EasyYeelight`, but Application name is **~~Easy~~Yeelight.app**.

You should run `sudo xattr -r -d com.apple.quarantine /Applications/Yeelight.app`

It's will be fine.

**Comment by xs0521** [comment]
> Project name is `EasyYeelight`, but Application name is **~Easy~Yeelight.app**.
> 
> You should run `sudo xattr -r -d com.apple.quarantine /Applications/Yeelight.app`
> 
> It's will be fine.

Thanks，I will update README
